package bigquery

//Bigquery struct reperesnts google analytics service.
type Bigquery struct {
}

type View  struct {
  DatasetID string `json:"datasetId"`
  ProjectID string `json:"projectId"`
  TableID   string `json:"tableId"`
}

type Access struct {
  Domain       string `json:"domain"`
  GroupByEmail string `json:"groupByEmail"`
  Role         string `json:"role"`
  SpecialGroup string `json:"specialGroup"`
  UserByEmail  string `json:"userByEmail"`
  view View  `json:"view"`
  }

type DatasetReference struct {
    DatasetID string `json:"datasetId"`
    ProjectID string `json:"projectId"`
  }

type AutoGenerated struct {
	access []Access `json:"access"`
	CreationTime     string `json:"creationTime"`
	datasetReference DatasetReference `json:"datasetReference"`
	DefaultTableExpirationMs string `json:"defaultTableExpirationMs"`
	Description              string `json:"description"`
	Etag                     string `json:"etag"`
	FriendlyName             string `json:"friendlyName"`
	ID                       string `json:"id"`
	Kind                     string `json:"kind"`
	LastModifiedTime string `json:"lastModifiedTime"`
	Location         string `json:"location"`
	SelfLink         string `json:"selfLink"`
}
